### ISSUE TITLE
Unable to download from Patreon

### ISSUE THREAD

**Issue by yul-oh895** [EndlessMISAKA/AtelierMisaka#1]
Hi, thank you for doing this app.

I was looking for something like this and hopefully I'm able to use it.

I tried using the Patreon downloader but it fails saying "UnKnown Error contact Please contact Developer"

I was able to follow the instructions from the Readme and logged into the account. I got the Supporter list added but after selecting a creator, it fails.

For reference, here is the error log
[error.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/4778966/error.log)

Thanks.

**Comment by EndlessMISAKA** [comment]
I am so sorry that I haven't seen github for a long time.
The error.log say the CEF browser doesn't initialize, it's unbelievable.
Could you tell me what did you do after you got the Supporter List?
Does you try it again after restart the software?
（by google translator）

**Comment by yul-oh895** [comment]
Hi, don't worry for the delay (sorry for the delay on my response too).

I followed the PDF manual on how to set it up.
After i updated the SupportList, I selected one of the creator/supported URL and clicked on OK to start the synthesis.
It tried load and then it gave the same error message I mentioned before.

I tried restarting and opening the software again. I also deleted it and re-downloaded it (First the 1.3.0 release and then 1.3.9)
It has not been fixed yet.
--------------------------
What is weird is that I was supporting 3 creators at the time and one of them worked with the synthesis but not the other two.

Let me know if you need more information.

**Comment by EndlessMISAKA** [comment]
Maybe the synthesis rule was wrong.
Could you tell me the creator URL who can't synthesis.

**Comment by EndlessMISAKA** [comment]
Maybe is null filename bug.
I release Ver1.3.11, you can try it again.

**Comment by yul-oh895** [comment]
Thank you for the release. I was able to update it to 1.3.12 and it worked for one of the creators that had this issue but this still occurs with another one: 

www.patreon.com user posts?u=14261425

I removed the "/" and inserted spaces in between but this is the URL

Also, I'm attaching the newest error log 
[error.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/4975006/error.log)


I found another issue but will open a new issue have everything more organized

**Comment by EndlessMISAKA** [comment]
Oh, I forgot this url format, maybe userId was wrong.
Open "Artist_Patreon.json" whitch is put in "Settings" folder.
Find string like 
{"Cid":"954327","Id":"954327","AName":"BaaBuu","PostUrl":"https://www.patreon.com/BaaBuu","Twitter":"","PayLow":"","PayLowInt":0,"PayHigh":"600","PayHighInt":600}
In here, "AName" is "藤宅仔", I need to know his "Cid" and "Id" and "PostUrl".
(those informations can get from Patreon web page, so don't worry about private data)
The true "Cid" and "Id" is "2146949".
If it is true, I need you help to fix this bug use some support data throw email if you don't mind.
Thank you.

And, I don't know why your error always say the browser doesn't initialized.
I want to know your action when this error occus.
So, follow those guide.
1. Delete error.log
2. Select a Patreon creator who can synthesis and do it.
3. If error occus or "error.log" appear, rename it to "error_can.log".
4. Select a Patreon creator who can't synthesis and do it.
5. If error occus or "error.log" appear, rename it to "error_nocan.log".

In Ver1.3.12, I update the readme.pdf, you can open it, and scorll to the last page, you can see the soft folder structure.
Or does you already install the "Microsoft Visual C++ Redistributable Package"?

**Comment by yul-oh895** [comment]
Hi, sorry for the delay. I was doing several things since this is a new month and I have a few new creators I'm following, including the same one from before.

I will first reply back with what you mentioned:

I was able to find the string for this creator and copy/pasted it exactly as it appears there.

{"Cid":"2146949","Id":"2146949","AName":"藤宅仔","PostUrl":"https://www.patreon.com/user?u=14261425","Twitter":"","PayLow":"","PayLowInt":0,"PayHigh":"300","PayHighInt":300}


>  If it is true, I need you help to fix this bug use some support data throw email if you don't mind.

I have a spare email that I don't use, let me know what do you need from me.

I follower your steps.
1. Deleted error.log
2. Selected a Patreon who worked (*more info on this later) and did it.
3. Renamed error to [error_can.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5026732/error_can.log)
4.Selected a Patreon who can't sythesis and pasted log as [error_nocan.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5026740/error_nocan.log)


I updated to version 1.3.13. My folder structure is the same 
![explorer_2020-08-05_01-18-28](https://user-images.githubusercontent.com/64549167/89383402-a3958380-d6b9-11ea-8da1-5c06fafb1e06.png)

What do you mean by "Or does you already install the "Microsoft Visual C++ Redistributable Package"?"
I searched on my PC and confirmed I have several versions installed: 2005, 2008, 2010, 2012, 2013, 2015-2019 and 2017. (They are exactly displayed like this).

I read online that Visual C++ Redistributable Package are not backwards compatible and certain applications require a specific version to work with. If this is true, could you confirm which version is required?

**Comment by yul-oh895** [comment]
Regarding what I mentioned before 
>Selected a Patreon who worked (*more info on this later) and did it.

With this new month, I started supporting some new creators so I used the UpdateSupportList button however, I noticed the same error happened just by updating (I forgot that this happened when I started using this).
Let me explain each step:

1. Open Atelier and selected Patreon
2. Select **UpdateSupportList** . It fails, see [error open.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5026793/error.open.log)
3. Closed Atelier

4. Open Atelier again, selected Patreon
5. Selected **Custom** from the dropdown list instead of leaving it blank. It worked.


After this, I tried using the same creator from this issue thread (_藤宅仔_) and found something:

1. If I select the creator and click on **OK**, it fails.
2. If I directly select **OK** again after closing the error message, it works and I can download the pictures.

The error_can.log file I attached on the above response is from this specific creator.

If I download the pictures from the creator and then change resipe with another artist, it works immediately without having to do the double **OK** process from above

Let me know your thoughts on this because I'm as clueless as you are.

**Comment by EndlessMISAKA** [comment]
Your "Microsoft Visual C++ Redistributable Package" is already installed, it's no problem.
But, I still don't know why the Browser Initialize always error.
Maybe the "debug.log" have some points.

Let's check somethings:
Your Windows10 is x64, right?
".Net Framework 4.7.1" is already installed, right?

**Comment by yul-oh895** [comment]
Hello,

Yes, Windows10 x64. I followed [online instructions](https://www.windowscentral.com/how-quickly-check-net-framework-version-windows-10#dotnet_version_registry) to find the NET Framework version and is 4.8.04084

Is this the correct version?

For the "debug.log" file, should I upload it directly here or do I need to edit it and post some information only?

**Comment by EndlessMISAKA** [comment]
About the .Net Framework, there are differences between different versions, so you can try to install version 4.7.1, download link is
https://www.microsoft.com/en-us/download/details.aspx?id=56116
About the "debug.log", rename to "debug_old.log" and open Atelier to make it error again, upload the "debug_old.log" and  "debug.log", thank you.

**Comment by yul-oh895** [comment]
I tried installing .NET framework again but it failed saying:

>.NET Framework 4.7.1 or a later update is already installed on this computer.

As for the steps above, i tried them and here are what I did exactly:

Just to clarify here, I re-subscribed to a creator that also failed when I started using Atelier but i stopped subscribing after the next month. I subscribed again this month to test it out.

The URL is www.patreon.com amagato (Same instructions as before, remove the space and add the "/" symbol.)

1. Open Atelier. Selected creator from the list and clicked **OK**. (Since the $ pledge was the same as before, I didn't change the "Cost"
2. It gave me the "_Unknown Error_" message. (I reviewed the debug.log file and only added an empty line with no text)
3. Clicked **OK** again. It gave error "_Internet Error, Please try again later_". (debug added the first two lines)
4. Clicked **UpdateSupportList**.
5. (same creator) I cliked **OK**. It started to load and count the posts but it failed and got stuck at 132 giving the "_Unknown Error_" again. (debug file added the rest of lines here).

Here are the [old_debug.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5073368/old_debug.log), new [debug.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5073369/debug.log) and new [error.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5073372/error.log)

I'm not sure if the new error message on "error.log" is due to the "Internet Error" error message or part of the same "Unknown Error".

**Comment by EndlessMISAKA** [comment]
Have you opened it with Administrator?
I see an error in "old_debug.log", it say "Unable to move the cache: Access is denied", I don't know what happened with it.
Delete "ChromiumCache" folder, and open soft with Administrator Mode.
I think the basic error is "Browser Initialize Error", could you download x86 browser core look like this:
![QQ截图20200815025024](https://user-images.githubusercontent.com/25360394/90283117-27155880-dea2-11ea-85a1-8e229a357264.jpg)

**Comment by yul-oh895** [comment]
Hi, sorry for the delay.

I re-downloaded all 3 zip files required (Core, x64 and x86), unzipped them on a new directory and placed them just like on your picture above.

Deleted Chromium and run AtelierMisaka.exe as Administrator.
Clicked on one of the creators and clicked OK. It gave the same error.
Click UpdateList button, logged into Patreon again.
Clicked OK and it seemed to start working.

But if I close it and run it again, when I select the creator and click on OK, the 1st time always fails and only works on the 2nd time I click OK.

Once again, the error.log file show these messages:

> 9/28/2020 7:01:36 PM
The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).
   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)
   at AtelierMisaka.PatreonUtils.<GetWebCode>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtelierMisaka.PatreonUtils.<InitBrowser>d__11.MoveNext()


>9/28/2020 7:05:20 PM
The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).
   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)
   at AtelierMisaka.PatreonUtils.<GetWebCode>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtelierMisaka.PatreonUtils.<InitBrowser>d__11.MoveNext()

>9/28/2020 7:06:05 PM
The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).
   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)
   at AtelierMisaka.PatreonUtils.<GetWebCode>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtelierMisaka.PatreonUtils.<InitBrowser>d__11.MoveNext()

>9/28/2020 7:40:01 PM
The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).
   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)
   at AtelierMisaka.PatreonUtils.<GetWebCode>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtelierMisaka.PatreonUtils.<InitBrowser>d__11.MoveNext()

>9/28/2020 7:42:26 PM
The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).
   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)
   at AtelierMisaka.PatreonUtils.<GetWebCode>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AtelierMisaka.PatreonUtils.<InitBrowser>d__11.MoveNext()
-----------------------------------------------

**Comment by EndlessMISAKA** [comment]
What about the debug.log?
The browser can't initialize, it must be the CefSharp error.
But the other users doesn't have this bug, so I don't know that is browser core error or your PC environment error.
