### ISSUE TITLE
Fantia下载图片403报错/403 error when downloading pictures from Fantia.

### ISSUE THREAD

**Issue by northtowertop** [EndlessMISAKA/AtelierMisaka#10]
错误日志/Error log.
最近几个月的投稿都没有问题，但是旧的投稿中的图片就全部403，mp4与mov等视频并没有影响。原投稿页可以打开，里面的图片也都可以查看。
The code works fine with the new recently posts, but gives a 403 error when downloading pictures in old posts, other files like mp4 and mov are not affected.

[error.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5443079/error.log)
[error_download.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5443080/error_download.log)

**Comment by northtowertop** [comment]
抓取的作者为全作品收费作者，如需要测试我可以提供cookies.
All the posts need payment to view, so I could supply cookies if needed.

**Comment by EndlessMISAKA** [comment]
加个扣扣详细聊聊？471125935

**Comment by WindBT47** [comment]
怎么解决的？我也遇到了
