### ISSUE TITLE
关于AtelierMisaka_FileManager移动资源的问题

### ISSUE THREAD

**Issue by Cyrker** [EndlessMISAKA/AtelierMisaka#16]
我发现老哥的这个项目好像有这样一个问题
比如说我想把某个作者的订阅全都放到这个文件夹
**..\作者ID\202010**
多次尝试发现不行
只能移动到 **..\作者ID**
然后问题来了..只要 **..\作者ID** 这个文件夹里的订阅，不管是几月份的，都会被移动到这个文件夹的里面来..

可能描述不是非常清楚，麻烦作者大大瞅一眼

**Comment by EndlessMISAKA** [comment]
嗷，抱歉，前几天在爆肝黄油，没看github
是要把所有内容移到某个特定目录下？
还是说把10月里的所有文件挪到10月的文件夹里？

**Comment by Cyrker** [comment]
是把10月的移到10月的目录里
 不好意思哈 描述不是很清晰

**Comment by EndlessMISAKA** [comment]
那新版的已经可以啦，你可以去试试了
