### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by Eclocksss** [EndlessMISAKA/AtelierMisaka#17]
log:
请求被中止: 未能创建 SSL/TLS 安全通道。
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 AtelierMisaka.FantiaUtils.GetWebCode(String url)
   在 AtelierMisaka.FantiaUtils.GetArtistListFromWebCode(String free, Int32 index)
   在 AtelierMisaka.FantiaUtils.<GetArtistList>b__7_0()

**Comment by EndlessMISAKA** [comment]
Fantia？？抱歉前几天在玩黄油没看github。
现在还有这个问题吗？有的话加我QQ详聊。471125935
