### ISSUE TITLE
Can I bypass paid subscriptions from fantia/Patreon with AtelierMisaka?

### ISSUE THREAD

**Issue by PascalGDDLC** [EndlessMISAKA/AtelierMisaka#19]
Can I download posts from subscription plans I am not subscribed to or in other words bypass the paywall and get normally paid posts for free?

**Comment by EndlessMISAKA** [comment]
Oh, no, sorry, it is impossible, please subscribe.
I create this soft is not to bypass the paywall.

**Comment by PascalGDDLC** [comment]
Oki, thank you for your answer!
