### ISSUE TITLE
No download costs more than 1,000yen at Fantia.

### ISSUE THREAD

**Issue by oku-kaz** [EndlessMISAKA/AtelierMisaka#2]
If I download that costs more than 1,000yen in fantia, the cost will be 000 and I can only download free data.

Very good app. Thanks.

**Comment by EndlessMISAKA** [comment]
Oh, I am so sorry.
Costs setting is  "0" and "1000", no "1,000".
Or you can make it empty, when cost is empty, it means 0 to infinity.

**Comment by EndlessMISAKA** [comment]
Oh no, I am so sorry again.
I know your means now.
That is my mistake, I will modify it soon.
Fantia doesn't have Pledge api, so I get cost from webpage.
The regular expression must be wrong.
Please wait for update.
Or you can make it empty to download contents before update.

**Comment by oku-kaz** [comment]
Thanks for the confirmation.
I was able to download it if I made it empty to empty.
I'm not in a hurry, so I hope you can respond. Thank you.

**Comment by EndlessMISAKA** [comment]
I am sorry for my delay.
Now I am waiting for my friend test.
Thank you for your issue, I will release after my friend test.

**Comment by EndlessMISAKA** [comment]
I have release the Ver1.3.13.
Thank you for your issue, it make my app better than before.
Thank you very much.

**Comment by oku-kaz** [comment]
The correct cost is now displayed.
Thank you very much. Keep up the good work!
