### ISSUE TITLE
2GBを超えるファイルのダウンロードエラー

### ISSUE THREAD

**Issue by noriokun4649** [EndlessMISAKA/AtelierMisaka#24]
ダウンロード中にクラッシュする現象が発生したため、調べてみたところ投稿に2GBを超えるファイルがアップロードされており、ダウンロード時にクラッシュしてしまう模様です。

これはおそらくDownloadItem.cs#314におけるバイト配列が2GBを超えるファイルの場合配列の上限である2147483647を超えてしまうのが原因だとおもわれます。

時間のあるときに修正していただければ幸いです。

**Comment by EndlessMISAKA** [comment]
あ、ごめんなさい、最近は受験勉強しててGithubを確認してません。
このバグは数が月前から発見しましたが、修正するのを忘れました、本当に申し訳ございません。
時間があれば修正します。

**Comment by EndlessMISAKA** [comment]
修正しましたよ

**Comment by noriokun4649** [comment]
ありがとうございます。
私の環境でも2GB以上でダウンロード出来ることを確認しました。
ありがとうございました。
