### ISSUE TITLE
Latest version of the app won't open on my laptop!

### ISSUE THREAD

**Issue by Rotalder01** [EndlessMISAKA/AtelierMisaka#25]
Hi so I downloaded your program off github but for some reason. It won't open on my laptop. Is there a way I can fix/open it?

Also, only the File Manager works when I open it.

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
Did you already downloaded Brownser Core in Version 1.4.1?

**Comment by Rotalder01** [comment]
Never mind. i downloaded it.
