### ISSUE TITLE
About the function to select the time.

### ISSUE THREAD

**Issue by gimanan** [EndlessMISAKA/AtelierMisaka#28]
Please write a specific example of the ability to choose a time. 

I wrote from 2021-06-01 00:00:00 to 2021-06-05 00:00:00:00, 
but it is still downloaded from the very beginning. 

Please help me.

**Comment by gimanan** [comment]
Then, if Lang's file is -1, the program itself cannot run, why?

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
About the select time function, please describe the situation in detail, it maybe a bug.
About the Lang's file, I think it can't be -1 by itself, but I didn't deal with -1, it's my miss.

**Comment by gimanan** [comment]
> Sorry for my delay.
> About the select time function, please describe the situation in detail, it maybe a bug.
> About the Lang's file, I think it can't be -1 by itself, but I didn't deal with -1, it's my miss.

I've been nervous because I haven't heard back for the past few days. Thank you for your reply.

**Comment by EndlessMISAKA** [comment]
Sorry, I just found a new job recently, so I didn't check GitHub.

Lang's bug maybe it's an IO problem, and select time bug maybe it's Value Update program.

I will release a new version on this weekend.

Sorry for my delay.

**Comment by EndlessMISAKA** [comment]
Fixed
