### ISSUE TITLE
Fantia doesn't only detects 1 new post at a time

### ISSUE THREAD

**Issue by yul-oh895** [EndlessMISAKA/AtelierMisaka#29]
When using the app to download the new posts from an user, it only detects one of them at a time.

For example:

I follow creator: https://fantia.jp/fanclubs/149052

I have already downloaded everything up until July 9. At the time of writing this issue, there are currently 17 new posts that  I have not downloaded.

If I run the app, it will detect the most recent one (https://fantia.jp/posts/807558) and download it but the search for new posts will end.

If I run the search again (editing the [Until date] section to July 9), it will detect the last 2 posts (the one downloaded already + 1 more), download it and finish the search.

If I run it again, it will detect 3 posts (the 2 that were downloaded already +1 more).

It never fully detects all missing posts and I need to manually search with the manual date in [Until] in order to get all new posts.

If you need further details, let me know.

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
Fixed already.
