### ISSUE TITLE
Duplicate file handling

### ISSUE THREAD

**Issue by thatguyinthebox** [EndlessMISAKA/AtelierMisaka#32]
Is it possible to add options for duplicate file handling? Sometimes the program will forget the previously downloaded posts when I upgrade the version. Whenever this happens, it will re-download everything with "_1" added to the end of the file. Is it possible to add an option to skip the download if the file already exists?

**Comment by EndlessMISAKA** [comment]
emm, don't forget move the Data.db file to new version folder.
And some post will re-download when the author update the attachments.
And it will check local file now.
