### ISSUE TITLE
Fantia 加载不出封面图或文件

### ISSUE THREAD

**Issue by SyuueenN** [EndlessMISAKA/AtelierMisaka#36]
头次使用，直接用来看 Fantia。按照要求准备好依赖和各种 id 后，点击确定，等了一小会。出现的是一大堆“没有封面”“文件：0”的版块。我想应该是很严重的 bug 了，希望留意一下。

顺带一提，您的工具是 Fantia 工具里功能性很不错且使用方便的了，可能因为看 Fantia 要下载的用户确实少吧。希望多多加油。

**Comment by EndlessMISAKA** [comment]
抱歉很久没有上GITHUB了，我看了一下：
首先关于那个“没有封面”“文件：0”的板块，【没有封面】因为直接加载封面很吃性能和网络，所以封面是会让用户自己手动点击获取封面。【文件：0】是因为你的帐号没有获取文件的权限，所以工具检测不到文件。
你需要先确认一下，是不是你没有登录fantia帐号？fantia不登录帐号的话，是什么东西都看不了的。
使用说明里面获取的cookies是针对于你已经在电脑上登录过后的cookies，这里面会包含你的登录信息，这样就能正常查看内容了。
