### ISSUE TITLE
Fanbox截取时间设置问题

### ISSUE THREAD

**Issue by Jerome-101** [EndlessMISAKA/AtelierMisaka#39]
在下载画师Fanbox图时，设置截取时间遇到了问题。
设置截取时间之后，在抓取的时候会抓到截取时间之前的往期的文章，导致下载量增大。

举例：设置截取时间为2022/01/01~2022/07/01之后，在画师A截取到了2021/03和2021/10的文章。我关掉软件重新打开，设置相同的时间，在另一个画师B那里则截取到了从2020/05开始的所有文章。

请教如果解决这个问题？谢谢你！

**Comment by Jerome-101** [comment]
感谢回复！

**Comment by Jerome-101** [comment]
感谢回复，首先是回答现象：在帖子列表里显示了。
然后是我的想法：我猜测应该是作者对帖子进行更新了（虽然我反反复复愣是没看出来更新在哪里qaq）。因为：

1. 我又测试了许多画师，只有上文提到的A、B这两个画师出现了这个问题，(我测试的)其他画师均能正常按设置时间来截取。
2. 设置时间从2022/07/01起，B画师不会截取到之前的文章。设置时间从2022/07/10起，A画师不会截取到之前的文章。
所以我推测是画师在上述时间点之前对帖子进行了更新。

我这边没有其他问题了，你可以关闭这个话题。感谢你开发的软件与你的解答！

**Comment by EndlessMISAKA** [comment]
emmm，现存的一种可能性是作者把【订阅价格改了】，就是那种，这个月支援的内容，下个月就让你看不到，然后要提高支援档位才行。这种现象出现的时候，你会在下载文件夹里看到两个名字几乎一模一样的文件夹（只有中间的价格数字不一样）
目前默认的文件夹命名规则是  时间_价格_帖子名字
