### ISSUE TITLE
使用困难

### ISSUE THREAD

**Issue by yae-rabbit** [EndlessMISAKA/AtelierMisaka#40]

**Comment by yae-rabbit** [comment]
System.Windows.Markup.XamlParseException: 对类型“AtelierMisaka.MainWindow”的构造函数执行符合指定的绑定约束的调用时引发了异常。 ---> System.DllNotFoundException: 无法加载 DLL“sqlite3”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

**Comment by EndlessMISAKA** [comment]
啊，抱歉，这几天出差了，QQ471125935
