### ISSUE TITLE
Files downloaded have half/less size than files downloaded manually

### ISSUE THREAD

**Issue by DisasterInbound** [EndlessMISAKA/AtelierMisaka#41]
Hello again,

I recently used the app and I noticed the downloaded files have a different (smaller) size than files that are manually downloaded on the website. They are usually half the size of the original file.

Although at first glance it doesn't appear there is a difference or loss of quality, I'm sure there is something being lost here that may be important. 

The attached file has an example of a file but this happened with all of them.  
[Files.zip](https://github.com/EndlessMISAKA/AtelierMisaka/files/9258767/Files.zip)
Atelier.jpg is the copy downloaded with the app and website.jpg was manually downloaded.

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
Regarding this phenomenon, a bug has been modified at [V1.3.17](https://github.com/EndlessMISAKA/AtelierMisaka/releases/tag/V1.3.17).
This bug will affect all lossy compressed pictures, like *.jpg files.
And the two pictures you had uploaded are different, maybe the source file is Atelier.jpg bigger then website.jpg
