### ISSUE TITLE
出现了一个编码的错误，但是错误日志没有输出当前正在处理的post id，我也不好去网页里面查是否有字符问题

### ISSUE THREAD

**Issue by esta0947** [EndlessMISAKA/AtelierMisaka#42]
无法将位于索引 743 处的 Unicode 字符 \uD83C 转换为指定的代码页。
   在 System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   在 System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   在 System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   在 System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   在 System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   在 System.IO.StreamWriter.Dispose(Boolean disposing)
   在 System.IO.TextWriter.Dispose()
   在 System.IO.File.InternalWriteAllLines(TextWriter writer, IEnumerable`1 contents)
   在 AtelierMisaka.ViewModels.VM_Download.<get_AddFantiaCommand>b__87_0(FantiaItem fi)
   在 AtelierMisaka.FantiaUtils.GetUrls(String pid, List`1 bis)
   在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
   在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
   在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
   在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
   在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
   在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
   在 AtelierMisaka.FantiaUtils.<>c__DisplayClass11_0.<GetPostIDs>b__0()

**Comment by EndlessMISAKA** [comment]
透露一下是哪个作者emmm，fantia的得查查看是什么情况

**Comment by esta0947** [comment]
> 透露一下是哪个作者emmm，fantia的得查查看是什么情况

https://fantia.jp/fanclubs/32900 抱歉回复的晚了，周末没上github

**Comment by EndlessMISAKA** [comment]
emmm，查了一下是 emoji 的转换问题，这个得想想办法
