### ISSUE TITLE
重复下载文件

### ISSUE THREAD

**Issue by Cathgao** [EndlessMISAKA/AtelierMisaka#43]
在下载fantia付费项目时，因为有下载失败的文件，所以完成一次下载之后重新打开软件再次下载同一作者的所有项目。但发现已经下载完的文件会被重复下载，文件名自动加上_1..._2
软件页面点亮了“检查本地文件”
请问一下如何能做到每次下载遇到重复而已经下载完成的文件自动跳过，只补全未下载完毕的内容，而不是再次下载重复的？
![image](https://user-images.githubusercontent.com/21031564/205502850-779992bc-5a1e-46bf-aaf5-dbffba0f145c.png)

**Comment by Cathgao** [comment]
然而我再一次重新下载之后发现，`error_download.log` 里面的文件又似乎是被下载了。请问对这个文件的正确理解是怎么样呢？

**Comment by EndlessMISAKA** [comment]
emmm抱歉回复晚了
这个检查本地文件是对比你的下载记录里面保存的文件路径，你上一次下载成功之后会把文件的存放位置保存在本地的数据库里，如果第二次下载的时候查找到这个记录对应的文件就会跳过。
有一种情况是，这个文件被作者更新过，这时候文件的下载链接就会改变，这样在数据库里就找不到对应的记录，看起来就像是重新下载了一样

**Comment by Cathgao** [comment]
> emmm抱歉回复晚了 这个检查本地文件是对比你的下载记录里面保存的文件路径，你上一次下载成功之后会把文件的存放位置保存在本地的数据库里，如果第二次下载的时候查找到这个记录对应的文件就会跳过。 有一种情况是，这个文件被作者更新过，这时候文件的下载链接就会改变，这样在数据库里就找不到对应的记录，看起来就像是重新下载了一样

我是在短时间内再次点击下载的，作者没有更新文件。但出现了重复下载并自动重命名的现象

**Comment by EndlessMISAKA** [comment]
emmm那有可能是fantia又更新了什么东西，你把软件目录下的data.db 文件发上来我查查看
