### ISSUE TITLE
[BUG] Fantia cookies 无法正确识别

### ISSUE THREAD

**Issue by jerryfangr** [EndlessMISAKA/AtelierMisaka#46]
# 环境
```
系统：Win10 22H2 x86_x64
软件：AtelierMisaka v1.5.15.2 + v1.4.1 浏览器内核 x86&x64
```

# 问题
- **Fantia 下载任意作者都提示Cookies问题，无法进行下载，`error.log`如下**
    ```
    2023/1/27 23:23:26
    远程服务器返回错误: (403) 已禁止。
       在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
       在 System.Net.WebClient.DownloadData(Uri address)
       在 AtelierMisaka.FantiaUtils.GetWebCode(String url)
       在 AtelierMisaka.FantiaUtils.GetUrls(String pid, List`1 bis)
       在 AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)
       在 AtelierMisaka.FantiaUtils.<>c__DisplayClass11_0.<GetPostIDs>b__0()
    ```

- **表现为点击开始，弹窗 `请确认Cookies是否过期`，弹出下载窗口但没有进行下载，倒是创建了下载目录。**
    ![Snipaste_2023-01-27_23-43-35](https://user-images.githubusercontent.com/75239387/215128918-b378deb6-5c7b-485c-9f99-80af274ad8c8.png)

<br/>

# 说明
- **此前我有测试成功下载过`77325`的作者，几个月没用，今天就任意作者都不行了。**

- **已重复退出登录，换过2次Cookie，重新覆盖安装软件，但依旧无效。**

- **错误与配置应该无关，处理目录都切换到默认配置也无用。**

- **去瞄了眼 `Data.db`，下载日志确实是空的**

<br/>

# 补充
**如果作者需要进一部的数据，可以留下你的公用邮箱和需要，我可以邮件发给你出错的Cookie等更多数据**

**顺带我看到`fantiadl`出现了类似的403问题，帖子中讨论是由于Fantia更新后`post`请求需要新增的 "X-CSRF-Token" 缺失带来的问题，这也许对你有用，点击这里可以前往 [fantiadl  issue 104](https://github.com/bitbybyte/fantiadl/issues/104)**

**Comment by EndlessMISAKA** [comment]
已经修复啦_(:3ゝ∠)_更新一下版本就可以了
