### ISSUE TITLE
Unable to download Fantia posts

### ISSUE THREAD

**Issue by DisasterInbound** [EndlessMISAKA/AtelierMisaka#49]
I tried to start download but it always shows an error message "Post Error: 1907955" (I believe the number is the post ID used on Fantia) even when trying a different creator.

The error.log file shows
`4/24/2023 1:44:37 AM`
`1907955`
 `at AtelierMisaka.FantiaUtils.GetPostIDsFromWebCode(String uid, Int32 index)`
 `at AtelierMisaka.FantiaUtils.<>c__DisplayClass13_0.<GetPostIDs>b__0()`

**Comment by EndlessMISAKA** [comment]
sorry, Fantia use the google cloud service, I will fix it in next version.
