### ISSUE TITLE
Fantia出現未知錯誤

### ISSUE THREAD

**Issue by carson1103** [EndlessMISAKA/AtelierMisaka#52]
看到大概讀到第3個帖文之後就會跑出錯誤

![image](https://github.com/EndlessMISAKA/AtelierMisaka/assets/51711065/eb533b00-44e4-4046-a145-d3ea48850758)

Error.log裡面看到的
19/5/2023 1:59:44
並未將物件參考設定為物件的執行個體。
   於 AtelierMisaka.FantiaUtils.<GetUrls>d__17.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 AtelierMisaka.FantiaUtils.<GetPostIDsFromWebCode>d__16.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 AtelierMisaka.FantiaUtils.<GetPostIDs>d__15.MoveNext()
-----------------------------------------------

**Comment by EndlessMISAKA** [comment]
啊，抱歉，最近在玩塞爾達，沒看Github，我會儘快調查原因

**Comment by EndlessMISAKA** [comment]
理論上應該已經解決這個問題了，你可以下載最新版本再試試看

**Comment by carson1103** [comment]
可以了
十分感激 >_<
