### ISSUE TITLE
打不開主程式:(

### ISSUE THREAD

**Issue by AriOwO** [EndlessMISAKA/AtelierMisaka#53]
[error.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/11602639/error.log)
嘗試打開時只會跳這個error

**Comment by EndlessMISAKA** [comment]
這個問題應該是電腦的安全策略導致的，你所下載的壓縮包應該是被鎖定的狀態，右鍵查看它的屬性，在下方【只讀】屬性的邊上是否有一個被勾選的【鎖定】或者【阻止】的選項？具體叫什麼名字我忘記了，取消它就可以了。
如果壓縮包沒有的話，就對解壓出來的文件做相同的操作。
