### ISSUE TITLE
无法打开浏览器

### ISSUE THREAD

**Issue by Jerome-101** [EndlessMISAKA/AtelierMisaka#54]
点击“打开浏览器”之后，画面变灰，右上角出现一个叉号，画面其他地方点击都没有反应了，我猜可能是浏览器覆盖了当前页面，但是没有正确显示浏览器的内容。能请作者大大帮忙看看是什么问题吗？谢谢！
![QQ20230801174207.jpg](https://www.z4a.net/images/2023/08/01/QQ20230801174207.jpg)

**Comment by jiut** [comment]
我也遇到了这种情况，开启代理后解决了

**Comment by EndlessMISAKA** [comment]
需要开启代理，如果你在国内的话。旧版本默认读取系统代理是个错误的做法，所以修复了，在版本更新的说明里有写。
