### ISSUE TITLE
内置浏览器无法使用谷歌账号登陆

### ISSUE THREAD

**Issue by Cathgao** [EndlessMISAKA/AtelierMisaka#55]
提示浏览器不安全
![image](https://github.com/EndlessMISAKA/AtelierMisaka/assets/21031564/14a1d38c-19a1-4f44-9d97-0574ae4ed856)

**Comment by Cathgao** [comment]
补充：下载fantia内容的时候，在已有cookie（以前填的）情况下，仍提示需要登陆，打开内置浏览器后无法使用Google账号登陆fantia

**Comment by EndlessMISAKA** [comment]
emmm我是直接使用cefsharp来做内核的，主要我不知道谷歌这个安全检测是怎么做的。不要用谷歌登录，在帐号密码那边输入谷歌帐号和密码进行登录就行了。如果你点击“用谷歌帐号进行登录”的按钮的话，不知道谷歌会做啥检测导致cefsharp过不了检测。

**Comment by Cathgao** [comment]
> emmm我是直接使用cefsharp来做内核的，主要我不知道谷歌这个安全检测是怎么做的。不要用谷歌登录，在帐号密码那边输入谷歌帐号和密码进行登录就行了。如果你点击“用谷歌帐号进行登录”的按钮的话，不知道谷歌会做啥检测导致cefsharp过不了检测。

我今天尝试了直接输入谷歌账号和密码登录，会直接提示邮箱或密码错误
不过因此我找回了fantia的独立密码并登录成功。
这个问题您来决定是否关闭吧

**Comment by EndlessMISAKA** [comment]
嗯，【直接点击（用谷歌帐号登录）会提示不安全】这个问题是从一开始就有的，最早是在Patreon那边的，我一直忘了说，下次更新的时候我看看会追加一下说明。
