### ISSUE TITLE
fantia無法下載

### ISSUE THREAD

**Issue by ChinaGon** [EndlessMISAKA/AtelierMisaka#59]
前幾天開始用1.6.5版本出現錯誤

今天用新的1.6.6仍然無法下載

以下為錯誤訊息
<img width="963" alt="未命名" src="https://github.com/EndlessMISAKA/AtelierMisaka/assets/80162889/5024cc52-c790-4b26-aacd-89156a0ad005">

![image](https://github.com/EndlessMISAKA/AtelierMisaka/assets/80162889/66679de4-a10e-4388-9909-a000f4e4329b)

**Comment by S0uTHBeaR** [comment]
我也有一樣的錯誤

**Comment by EndlessMISAKA** [comment]
已在1.6.7版本进行修复
