### ISSUE TITLE
cannot download from Patreon JSON Error

### ISSUE THREAD

**Issue by tbcollins12** [EndlessMISAKA/AtelierMisaka#6]
When trying to download from Patreon, selecting option "Update SupportList" gives error "UnKnown Error Please Contact Programmer".

I ignore this, and click "OK" to begin download. It goes through about 80 posts before failing with this error
"Can not resolve JSON data Please Contact Progammer"

Error log attached.
[error.log](https://github.com/EndlessMISAKA/AtelierMisaka/files/5216044/error.log)

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
Could you tell me the creator name or url ?

**Comment by tbcollins12** [comment]
https://www.patreon.com/robotswithrayguns

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 26, 2020 at 9:08 AM, EndlessMISAKA<notifications@github.com> wrote:   


Sorry for my delay.
Could you tell me the creator name or url ?

**Comment by EndlessMISAKA** [comment]
I have release Ver1.4.1, you can try it again.
