### ISSUE TITLE
Fanbox一直显示IDName与登录账号不一致

### ISSUE THREAD

**Issue by Kilar0409** [EndlessMISAKA/AtelierMisaka#60]
![1695853583656](https://github.com/EndlessMISAKA/AtelierMisaka/assets/121296201/178de8d6-2c12-4a16-abcb-d38d8029d125)
![1695853561200](https://github.com/EndlessMISAKA/AtelierMisaka/assets/121296201/018f4ab0-4b29-4598-b524-60182f36aa4c)
如图，IDName那里一直显示与登录账号不一致，试了多少次都没用，改了ID也不行

**Comment by EndlessMISAKA** [comment]
啊。不是这个ID。fanbox因为是pixiv名下的，所以它没有一个能直接获取到用户名的接口，所以用的是Pixiv里的数字ID，readme里面有写，是在pixiv个人信息页面的【网址】里面，你再重新试一下
