### ISSUE TITLE
Why is Trojan in release zip?

### ISSUE THREAD

**Issue by j8o4pvnEY9WC** [EndlessMISAKA/AtelierMisaka#7]
I downloaded the released zip and Windows Defender detected "Trojan:Script/Wacatac.B!ml".
Why is there a Trojan in the zip file?

**Comment by yul-oh895** [comment]
I'm also joining as this is concerning.
I redownloaded all 4 necessary zip files (3 from Core 1.3.0 and 1 from latest release 1.3.18) and scanned them but I was unable to find the trojan.

>From [release 1.3.0](https://github.com/EndlessMISAKA/AtelierMisaka/releases/tag/V1.3.0)

AtelierMisaka_Soft_1.3.0.zip
https://www.virustotal.com/gui/file/f5c499963103d6d58c4fc1a7db7e91847ba1f4dc939c6a4a6594bf4150236966/details

AtelierMisaka_Browser_x86.zip
https://www.virustotal.com/gui/file/28e1918cba90bd85155ebd585d4796bf0580be089742728322fdb6eabb0cba9e/detection

AtelierMisaka_Browser_x64.zip
https://www.virustotal.com/gui/file/549710ba474b01082b82e23631e5335b2b96b2923238faac2582e90dd4e33acb/detection

>From [latest release 1.3.18](https://github.com/EndlessMISAKA/AtelierMisaka/releases/tag/V1.3.18)

AtelierMisaka_Soft_1.3.18.zip
https://www.virustotal.com/gui/file-analysis/OGE1YmFiMDIwZTBmYTQyZTdiZTVhZjhmNWU2MjQ4NjA6MTYwMDM2NzMxOQ==/detection


Do you know which specific file had the trojan?

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
This program is a Web Crawler, maybe system think it has some security matters.
