### ISSUE TITLE
하는 법 모르면 중갤 왜함?ㅋㅋㅋㅋㅋ

### ISSUE THREAD

**Issue by dhtpdud** [EndlessMISAKA/AtelierMisaka#8]
1. Lang.ini 파일을 열면 -1로 되어 있으실 겁니다. 2로 바꾸십시오.
(0= 중국어, 1=일본어, 2=영어)

2. sqlite3.dll **x64** 를 실행파일과 같이 두십시오.

**Comment by EndlessMISAKA** [comment]
I am sorry , I can't understand Korean.
