### ISSUE TITLE
Feature Request: Add hyperlinks to txt files.

### ISSUE THREAD

**Issue by yul-oh895** [EndlessMISAKA/AtelierMisaka#9]
Sometimes creators don't add the files directly to their page and instead use an online archive website (Mega, Dropbox, etc.)

So normally you would need to click on the link to download the file however, if you download a post from them that includes the link on the description, it is not added to the "Comment.txt" file.

Example:

On the Patreon page it will say
>[Click here to download the archive](example.com)

but on the txt file it only shows the literal text 

>Click here to download the archive

 but doesn't add the hyperlink of the website

I've not noticed if this behavior is the same for Fantia and Fanbox but if it is, it would be really useful to add the hyperlinks to the same txt files used on the 3 websites when saving the post description.

**Comment by yul-oh895** [comment]
Also if this is added, would there be a way to re-download all Comment.txt files?

As currently all the txt files doesn't include the hyperlinks, I would like to re-download only the txt files without having to include the media files previously downloaded.

**Comment by EndlessMISAKA** [comment]
Sorry for my delay, maybe it is an Embed Item.
I will send mail to you.

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
In this case, I need jsondata.
Open the Posts page, use F12 like "get cookie".
[image: QQ截图20201001091749.jpg]
Filter with "posts?include=c".
In Patreon, posts page will show 20 posts in one page, so if the error post
is No.31, you should "Load more", and select second package like this:
[image: QQ截图20201001092355.jpg]
Copy All in the "Response", paste into a new txt file and send it to me.
Thank you.

yul-oh895 <notifications@github.com> 于2020年9月27日周日 下午2:50写道：

**Comment by EndlessMISAKA** [comment]
Sorry for my delay.
In this case, I need jsondata.
Open the Posts page, use F12 like "get cookie".
![QQ截图20201001091749](https://user-images.githubusercontent.com/25360394/94755987-d792d980-03c8-11eb-962c-c5164028b6e8.jpg)
Filter with "posts?include=c".
In Patreon, posts page will show 20 posts in one page, so if the error post is No.31, you should "Load more", and select second package like this:
![QQ截图20201001092355](https://user-images.githubusercontent.com/25360394/94755991-dbbef700-03c8-11eb-8128-f429a2af2e82.jpg)
Copy All in the "Response", paste into a new txt file and send it to me.
Thank you.

**Comment by yul-oh895** [comment]
Hi, I'm really sorry for the delay.

I tried the steps you detailed but just a minor thing, I did not find anything with "posts?include=c" like you mentioned, only with "posts?include=" which I found one

However, how can I copy and paste everything on the Response tab. 

Everything is only showing up like this:

**Comment by EndlessMISAKA** [comment]
You can copy this link and open it in a new browser tab, the Response will show in web like text.

**Comment by yul-oh895** [comment]
Thanks. Here is the text file of one of the posts that have a hyperlink
[hyperlink post.txt](https://github.com/EndlessMISAKA/AtelierMisaka/files/5572138/hyperlink.post.txt)

**Comment by EndlessMISAKA** [comment]
This response has no useful content, use this link
[hyperlink.txt](https://github.com/EndlessMISAKA/AtelierMisaka/files/5572267/hyperlink.txt)
I will delete it after I get it.

**Comment by yul-oh895** [comment]
Sorry for that one. Maybe this will work
[posts #1.txt](https://github.com/EndlessMISAKA/AtelierMisaka/files/5572361/posts.1.txt)

**Comment by EndlessMISAKA** [comment]
Which one has hyperlink?

**Comment by yul-oh895** [comment]
The post title should be "Rias Gremory :: full version"

Here is a screenshot of how it looks like

![waterfox_2020-11-20_03-04-07](https://user-images.githubusercontent.com/64549167/99781390-6a084d00-2add-11eb-8c36-7b65006d09d8.png)

I followed the steps exactly as you mentioned so I hope it was able to work but I'm not sure why it is not showing up on the txt file

**Comment by EndlessMISAKA** [comment]
OK, I know what you mean, but this post doesn't in that txt file. Use this:
[hyperlink_1.txt](https://github.com/EndlessMISAKA/AtelierMisaka/files/5572528/hyperlink_1.txt)

**Comment by yul-oh895** [comment]
I think this time we made it. Here you go

[post hyperlink.txt](https://github.com/EndlessMISAKA/AtelierMisaka/files/5572550/post.hyperlink.txt)

**Comment by thatguyinthebox** [comment]
Hi, 

This does not appear to be working on Pixiv Fanbox posts. Here is an example screenshot from two posts:

Post #1 - https://www.fanbox.cc/@janyhero/posts/1044935 - Open to public:
![image](https://user-images.githubusercontent.com/79183943/108155844-9405e700-70ad-11eb-9efe-ea688c83d214.png)

Post #2 - https://janyhero.fanbox.cc/posts/1044889 - Paid post:
![image](https://user-images.githubusercontent.com/79183943/108155894-ae3fc500-70ad-11eb-94ec-759debb2b597.png)

For Post #1, it is open to public so I will allow you to check it. 

For Post #2, I found this in the Network sources that looks like it has the post content, I hope this is helpful:
![image](https://user-images.githubusercontent.com/79183943/108156383-9583df00-70ae-11eb-98d2-47b3577f2558.png)

I have attached the contents of this so that you can review. 
[postId=1044889.txt](https://github.com/EndlessMISAKA/AtelierMisaka/files/5993227/postId.1044889.txt)

**Comment by thatguyinthebox** [comment]
Also for reference, I have attached the two comment.html that AtelierMisaka downloads for these two posts:
[Comment.zip](https://github.com/EndlessMISAKA/AtelierMisaka/files/5993238/Comment.zip)

**Comment by yul-oh895** [comment]
Sorry, I closed it accidentally. 

But I wasn't sure f this may needed to be closed since this is now possible to do it.
